from app.services.component_catalog_service_postgres import ComponentCatalogPostgresService


ComponentCatalogService = ComponentCatalogPostgresService
catalog_service = ComponentCatalogPostgresService()
