#!/usr/bin/env bash
# Mint a long-lived KiCad-provider access token for remote-panel load tests.
# Writes credentials to loadtest/.env.loadtest (gitignored).
#
# Uses provider_auth_service.issue_token inside the running backend container —
# same token shape KiCad gets after REMOTE_LOGIN (scope remote_symbols.read).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/loadtest/.env.loadtest"
CONTAINER="${PRISM_BACKEND_CONTAINER:-kicad-prism-backend}"
TTL_SECONDS="${PRISM_LOADTEST_TOKEN_TTL_SECONDS:-7200}"

if ! docker inspect "$CONTAINER" >/dev/null 2>&1; then
  echo "Backend container '$CONTAINER' is not running." >&2
  exit 1
fi

mkdir -p "${ROOT}/loadtest"

echo "Minting remote_symbols.read access token in ${CONTAINER} (ttl=${TTL_SECONDS}s)..."

TOKEN="$(
  docker exec -i -e TTL_SECONDS="$TTL_SECONDS" "$CONTAINER" python - <<'PY'
import os
from app.services import provider_auth_service

ttl = int(os.environ.get("TTL_SECONDS") or "7200")
token = provider_auth_service.issue_token(
    token_type="access",
    email="remote-panel-loadtest@local",
    name="Remote Panel Loadtest",
    picture="",
    role="viewer",
    scope="remote_symbols.read",
    ttl_seconds=ttl,
)
print(token)
PY
)"

if [[ -z "$TOKEN" || "$TOKEN" != v1.* ]]; then
  echo "Failed to mint provider access token." >&2
  exit 1
fi

umask 077
cat >"$OUT" <<EOF
# Generated by scripts/bootstrap_remote_panel_loadtest_client.sh — do not commit.
# KiCad-shaped provider access token (remote_symbols.read). Expires in ${TTL_SECONDS}s.
PRISM_LOADTEST_BEARER_TOKEN=${TOKEN}
EOF

echo "Wrote ${OUT}"

CAT_HTTP="$(
  curl -sS -o /tmp/prism-loadtest-categories.json -w '%{http_code}' \
    -H "Authorization: Bearer ${TOKEN}" \
    "http://127.0.0.1:8080/api/remote-provider/categories"
)"
echo "Categories probe HTTP ${CAT_HTTP}."
if [[ "$CAT_HTTP" != "200" ]]; then
  cat /tmp/prism-loadtest-categories.json >&2 || true
  exit 1
fi

COUNT="$(python3 -c 'import json; print(len(json.load(open("/tmp/prism-loadtest-categories.json")).get("categories") or []))')"
echo "Auth OK — ${COUNT} categories visible."
echo "Ready. Run: docker compose -f docker-compose.loadtest.yml up --build --abort-on-container-exit"
