#!/usr/bin/env python3
"""Generate the frontend's catalog workflow presentation contract.

The backend policy in ``backend/app/services/catalog/workflow_policy.py`` is
authoritative. This writes it as a TypeScript module the frontend reads to
decide which workflow transitions to offer; the server still authorizes every
request. ``backend/tests/test_workflow_policy.py`` fails when the committed
module no longer matches the policy, so a policy change always ships with a
regeneration.

Usage::

    python3 scripts/export_workflow_policy.py            # write the module
    python3 scripts/export_workflow_policy.py --check    # exit 1 on drift
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND_ROOT = REPO_ROOT / "backend"
OUTPUT_PATH = REPO_ROOT / "frontend" / "src" / "lib" / "catalog-workflow-policy.generated.ts"

sys.path.insert(0, str(BACKEND_ROOT))

from app.services.catalog.workflow_policy import workflow_policy_contract  # noqa: E402


def render_module() -> str:
    contract = json.dumps(workflow_policy_contract(), indent=2, sort_keys=False)
    return (
        "// Generated by scripts/export_workflow_policy.py from\n"
        "// backend/app/services/catalog/workflow_policy.py. Do not edit by hand;\n"
        "// backend/tests/test_workflow_policy.py fails when this file is stale.\n"
        "//\n"
        "// The server authorizes every transition. This contract only decides which\n"
        "// transitions the client offers.\n"
        "\n"
        "export const CATALOG_WORKFLOW_POLICY = "
        + contract
        + " as const;\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 when the committed module differs")
    args = parser.parse_args(argv)
    rendered = render_module()
    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != rendered:
            print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is stale; run scripts/export_workflow_policy.py", file=sys.stderr)
            return 1
        print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} matches the workflow policy")
        return 0
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
