"""Workspace schema migration 6: thumbnail_source.

Frozen. Applied deployments recorded this body in ``ws_schema_migrations``;
edit nothing here, add a new migration instead.
"""

from __future__ import annotations

from typing import Any


def migrate(conn: Any) -> None:
    """Record whether a thumbnail is committed in the repo or generated by Prism.

    Generated thumbnails moved out of the Git checkout, so `thumbnail_rel` alone
    no longer says where to read one from. Existing rows all predate the move
    and resolve inside the checkout, which is what the default describes.
    """
    conn.execute(
        """
        ALTER TABLE ws_projects
            ADD COLUMN IF NOT EXISTS thumbnail_source TEXT NOT NULL DEFAULT 'repository'
        """
    )
