// Generated by scripts/export_workflow_policy.py from
// backend/app/services/catalog/workflow_policy.py. Do not edit by hand;
// backend/tests/test_workflow_policy.py fails when this file is stale.
//
// The server authorizes every transition. This contract only decides which
// transitions the client offers.

export const CATALOG_WORKFLOW_POLICY = {
  "stages": [
    "open",
    "in_progress",
    "qa_review",
    "done",
    "released",
    "archived"
  ],
  "legacyAliases": {
    "draft": "open",
    "in_review": "qa_review",
    "qa_approved": "done",
    "released": "released",
    "deprecated": "archived"
  },
  "transitions": {
    "open": [
      "in_progress",
      "archived"
    ],
    "in_progress": [
      "qa_review",
      "open",
      "archived"
    ],
    "qa_review": [
      "done",
      "in_progress",
      "archived"
    ],
    "done": [
      "released",
      "qa_review",
      "archived"
    ],
    "released": [
      "archived",
      "open"
    ],
    "archived": [
      "open"
    ]
  },
  "allowed": {
    "viewer": {
      "open": [],
      "in_progress": [],
      "qa_review": [],
      "done": [],
      "released": [],
      "archived": []
    },
    "designer": {
      "open": [
        "in_progress",
        "archived"
      ],
      "in_progress": [
        "qa_review",
        "open",
        "archived"
      ],
      "qa_review": [
        "in_progress",
        "archived"
      ],
      "done": [
        "released",
        "qa_review",
        "archived"
      ],
      "released": [
        "archived",
        "open"
      ],
      "archived": [
        "open"
      ]
    },
    "qa": {
      "open": [],
      "in_progress": [],
      "qa_review": [
        "done",
        "in_progress",
        "archived"
      ],
      "done": [],
      "released": [],
      "archived": []
    },
    "admin": {
      "open": [
        "in_progress",
        "archived"
      ],
      "in_progress": [
        "qa_review",
        "open",
        "archived"
      ],
      "qa_review": [
        "done",
        "in_progress",
        "archived"
      ],
      "done": [
        "released",
        "qa_review",
        "archived"
      ],
      "released": [
        "archived",
        "open"
      ],
      "archived": [
        "open"
      ]
    }
  }
} as const;
