/**
 * Tracker UI fixtures for tests. Not imported by production code so mocks stay
 * out of the client bundle.
 */

import type {
    CommentTrackerProjection,
    ConnectorHealth,
    ProjectTrackerSettings,
    TrackerConnector,
    UserIdentity,
} from "@/types/trackers";

/** Canonical examples plus overlay states for UI tests. Shared fixtures stay untouched. */
export const trackerUiMocks = {
    destination: {
        connectorId: "cn_gh1",
        containerKind: "repo" as const,
        containerPath: "acme/openswitch",
        remoteContainerId: "987654321",
        generation: 2,
        visibility: "private" as const,
    },
    connector: {
        id: "cn_gh1",
        provider: "github",
        displayName: "GitHub.com",
        instanceKind: "github.com",
        baseUrl: "",
        bot: { id: "199001", login: "prism[bot]" },
        credentialConfigured: true,
        webhookConfigured: true,
        webhookUrl: "https://prism.example/api/trackers/webhooks/github/cn_gh1",
        oauthClientConfigured: true,
        paused: false,
        pausedReason: null,
        writesEnabled: true,
        auditCount: 1,
    } satisfies TrackerConnector,
    pausedConnector: {
        id: "cn_gh1",
        provider: "github",
        displayName: "GitHub.com",
        instanceKind: "github.com",
        baseUrl: "",
        bot: { id: "199001", login: "prism[bot]" },
        credentialConfigured: true,
        paused: true,
        pausedReason: "auth",
        writesEnabled: false,
        auditCount: 1,
    } satisfies TrackerConnector,
    health: {
        connectorId: "cn_gh1",
        paused: false,
        lastWebhookAt: "2026-09-20T15:42:12Z",
        lastPollAt: "2026-09-20T15:30:00Z",
        lastSweepAt: "2026-09-20T12:00:00Z",
        pendingOps: 2,
        sentOps: 0,
        quarantinedOps: 0,
        failedOps: 0,
        oldestPendingOpAge: "PT4M",
        oldestUnappliedHintAge: "PT0S",
        rateLimitResumeAt: null,
        degraded: false,
        lastError: null,
    } satisfies ConnectorHealth,
    projectSettings: {
        projectId: "prj_47c2551996d0",
        connectorId: "cn_gh1",
        projectRepoPath: "acme/openswitch",
        destination: {
            containerKind: "repo" as const,
            containerPath: "acme/openswitch",
            remoteContainerId: "987654321",
            generation: 2,
            visibility: "private" as const,
        },
        acknowledgement: {
            visibility: "private" as const,
            acknowledgedBy: "u_admin",
            acknowledgedAt: "2026-09-18T09:00:00Z",
            valid: true,
        },
        autoMinSeverity: "minor",
        autoTaskClass: true,
        promoteMinRole: "designer",
        labels: {
            base: "prism",
            severityPrefix: "severity:",
            classPrefix: "class:",
            boardPrefix: "board:",
        },
    } satisfies ProjectTrackerSettings,
    publicAckRequired: {
        projectId: "prj_47c2551996d0",
        connectorId: "cn_gh1",
        destination: {
            containerKind: "repo" as const,
            containerPath: "acme/openswitch",
            remoteContainerId: "987654321",
            generation: 2,
            visibility: "public" as const,
        },
        acknowledgement: {
            visibility: "private" as const,
            acknowledgedBy: "u_admin",
            acknowledgedAt: "2026-09-18T09:00:00Z",
            valid: false,
        },
        autoMinSeverity: "minor",
        autoTaskClass: true,
        promoteMinRole: "designer",
        labels: {
            base: "prism",
            severityPrefix: "severity:",
            classPrefix: "class:",
            boardPrefix: "board:",
        },
    } satisfies ProjectTrackerSettings,
    identity: {
        connectorId: "cn_gh1",
        provider: "github",
        forgeUserId: "5550001",
        forgeLogin: "arjun-gh",
        scopes: ["read:user"],
        linkedAt: "2026-09-19T11:20:00Z",
        expiresAt: "2026-09-20T19:20:00Z",
        status: "active" as const,
    } satisfies UserIdentity,
    revokedIdentity: {
        connectorId: "cn_gh1",
        provider: "github",
        forgeUserId: "5550001",
        forgeLogin: "arjun-gh",
        scopes: ["read:user"],
        linkedAt: "2026-09-19T11:20:00Z",
        expiresAt: "2026-09-20T19:20:00Z",
        status: "revoked" as const,
    } satisfies UserIdentity,
    linkedProjection: {
        linkState: "linked" as const,
        provider: "github",
        externalId: "412",
        externalUrl: "https://github.com/acme/openswitch/issues/412",
        destination: {
            connectorId: "cn_gh1",
            containerPath: "acme/openswitch",
            containerKind: "repo",
            generation: 2,
        },
        remoteState: "open",
        remoteUpdatedAt: "2026-09-20T15:42:11Z",
        pendingIntent: null,
        syncState: "confirmed",
        pausedReason: null,
        bodyAuthority: "prism",
        lastError: null,
    } satisfies CommentTrackerProjection,
    pendingIntentProjection: {
        linkState: "linked" as const,
        provider: "github",
        externalId: "412",
        remoteState: "open",
        pendingIntent: "set_state:closed",
        syncState: "sent",
        pausedReason: null,
        bodyAuthority: "prism",
        lastError: null,
    } satisfies CommentTrackerProjection,
    conflictError: {
        detail: "Comment changed since revision 1",
        code: "revision_conflict",
        currentRevision: 3,
    },
    publicationDenied: {
        detail: "Resolving a linked thread requires the designer role on this project",
        code: "publication_required",
        requiredRole: "designer",
    },
    providerRateLimited: {
        class: "rate_limited" as const,
        message: "GitHub secondary rate limit; retry after 2026-09-20T16:20:00Z",
        resumeAt: "2026-09-20T16:20:00Z",
        status: 403,
        retryable: true,
    },
};
